import Head from 'next/head'
import { useAddress } from '@thirdweb-dev/react'

export default function Home() {

  const address = useAddress();

  if(!address)
  {
    return 'Connect with metamask'
  }


  return (
    <>
      <Head>
        <title>Nft-Drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='flex  p-5 border-2 h-[50vh] text-white  hover:text-red-600/75 bg-black  justify-center items-center'>Heyy</h1>
    </>
  )
}
